datamodule:
  _target_: tumor_semseg.data.brain_mri_datamodule.BrainMRIDataModule
  config:
    _target_: tumor_semseg.data.brain_mri_datamodule.BrainMRIDataModuleConfig
    dataset_dirpath:
      _target_: pathlib.Path
      _args_: ["data/kaggle_3m"]
    seed: ${seed}
    batch_size: 32
    augment: true
    num_workers: 6
    image_size: [256, 256]
