defaults:
  - override /hydra/sweeper: optuna

hydra:
  run:
    dir: "."
  output_subdir: null
  sweeper:
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: ${seed}
      n_startup_trials: 2
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    direction: maximize
    storage: null
    study_name: tumorsemseg
    n_jobs: 1
    n_trials: 20
    params:
      lr: interval(0.0001, 0.1)
      batch_size: choice(8, 16, 32, 64, 128, 256)
