defaults:
  - datamodule
  - module
  - trainer
  - hydra
  - _self_

tumor_semseg_version:
  _target_: tumor_semseg.__version__
seed: null
checkpoint: null
find_initial_lr: true
n_classes: 1
in_channels: 3
image_size: [256, 256]

datamodule:
  config:
    dataset_dirpath:
      _args_: ["data/kaggle_3m"]

trainer:
  logger:
    experiment: tumorsemseg_v0
