defaults:
  - model: deeplab

module:
  _target_: tumor_semseg.module.brain_mri_module.BrainMRIModule
  config:
    _target_: tumor_semseg.module.brain_mri_module.BrainMRIModuleConfig
    model: ${model}
    loss:
      _target_: tumor_semseg.loss.semseg_losses.TverskyLoss
    optimizer:
      _target_: tumor_semseg.optimize.optimizer.adamax
    scheduler:
      _target_: tumor_semseg.optimize.scheduler.lambda_lr
    bin_det_threshold: 0.5
    example_input_array_shape:
      [
        1,
        "${model.config.in_channels}",
        "${datamodule.config.image_size.0}",
        "${datamodule.config.image_size.1}",
      ]
