defaults:
  - model: smp

module:
  _target_: tumor_semseg.module.brain_mri_module.BrainMRIModule
  config:
    _target_: tumor_semseg.module.brain_mri_module.BrainMRIModuleConfig
    model: ${model}
    loss:
      _target_: tumor_semseg.loss.semseg_losses.CELoss
    optimizer:
      _target_: tumor_semseg.optimize.optimizer.adam
    scheduler:
      _target_: tumor_semseg.optimize.scheduler.lambda_lr
    bin_det_threshold: 0.5
    example_input_array_shape:
      [1, "${in_channels}", "${image_size.0}", "${image_size.1}"]
    qat: null # experimental feature
      # _target_: tumor_semseg.module.brain_mri_module.QuantizationConfig
      # qconfig: x86
      # auto_fuse_modules: true
      # check_quantization: false
