_target_: tumor_semseg.architecture.deeplab.DeepLabv3
config:
  _target_: tumor_semseg.architecture.deeplab.DeepLabv3Config
  n_classes: 1
  in_channels: 3
  model_version_key: mobilenet
  pretrained: False
