# Check all available models in: https://github.com/qubvel/segmentation_models.pytorch
_target_: segmentation_models_pytorch.decoders.unetplusplus.model.UnetPlusPlus
encoder_name: mobilenet_v2
encoder_weights: imagenet
decoder_use_batchnorm: true
in_channels: ${in_channels}
classes: ${n_classes}
activation: null
