# Check https://github.com/qubvel/segmentation_models.pytorch for available models
_target_: segmentation_models_pytorch.UnetPlusPlus
encoder: resnext50_32x4d
encoder_weights: imagenet
in_channels: ${in_channels}
classes: ${n_classes}
activation: sigmoid
