_target_: tumor_semseg.architecture.unet.UNet
config:
  _target_: tumor_semseg.architecture.unet.UNetConfig
  n_classes: 1
  in_channels: 3
  activation:
    _target_: torch.nn.ReLU
    inplace: true
  bilinear: false
